# Generated by Django 3.2 on 2021-05-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('photoUrl', models.CharField(max_length=2000)),
                ('adv_id', models.IntegerField()),
            ],
        ),
    ]
